export const ELEMENT_REMOVED = 'ELEMENT_REMOVED';
export const ELEMENT_ADDED = 'ELEMENT_ADDED';
export const ELEMENT_EXCHANGE = 'ELEMENT_EXCHANGE';
export const COUNTER_SAVED = 'COUNTER_SAVED';
export const COUNTER_ADDED = 'COUNTER_ADDED';